Changes needed to complete a build. changed java from 14 to 8 added gxt.triton.themes and gxt jar files put jooq files, needed during install to a folder in project jooq added folder installdir to contain files under source control used only in installation or when running added commons-io added commons-io-fileupload
NOTE:  jars added by junaid are in web-inf/lib, move the new onese there instead of getting from jar folder

Run does not show in project but debug does.  When debug is clicked the following error occurs

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size.